# Generated by Django 5.0 on 2023-12-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=60, verbose_name='автор')),
                ('mail', models.EmailField(max_length=70, verbose_name='почта')),
                ('description', models.TextField(max_length=50, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Активно'), ('blocked', 'В Заблокировано')], default='active', max_length=20, verbose_name='Статус')),
            ],
        ),
    ]
